from django.urls import path
from.import views
urlpatterns=[
    path('add_scheme',views.add_scheme),
    path('add_sub_scheme',views.add_sub_scheme),
    path('add_products',views.products),
    path('edit_schemes/<int:id>',views.edit_scheme),
    path('delete_schemes/<int:id>', views.delete_schemes),
    path('view_sub_schemes',views.view_sub_schemes),
    path('view_add_products',views.view_add_products),
    path('view_applied_schemes',views.view_applied_schemes),
    path('edit_products/<int:id>',views.edit_products),
    path('delete_products/<int:id>', views.delete_products),
    path('add_news',views.add_news),
    path('view_add_news',views.view_add_news),
    path('edit_news/<int:id>',views.edit_news),
    path('delete_news/<int:id>', views.delete_news),
    path('view_booking',views.view_booking),
    path('view_query',views.view_query),
    path('response/<int:id>',views.response),
    path('profile',views.profile),
    path('edit_profile',views.edit_profile),
    path('vw_insurance_book',views.vw_insurance_book),
    path('vw_electri_book',views.vw_electri_book),
    path('vw_pension_book',views.vw_pension_book),
    path('vw_state_h_m_book',views.vw_state_h_m_book),
    path('vw_pm_k_book',views.vw_pm_k_book),
    path('edit_officer',views.edit_officer),
    path('edit_farmer',views.edit_farmer),
    path('edit_shops',views.edit_shops),
   ]