# Generated by Django 4.2.2 on 2023-06-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_farmer',
        ),
    ]
