# Generated by Django 4.2.2 on 2023-06-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_user_farmer_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_farmer',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_farmer',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
