# Generated by Django 4.2.2 on 2023-08-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_register_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
