# Generated by Django 4.2.2 on 2023-08-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_register_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='aadhar',
            new_name='aadhar_number',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='number',
            new_name='contact_number',
        ),
    ]
