# Generated by Django 4.2.2 on 2023-07-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0006_register_aadhar_register_panchayath_register_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default='', max_length=50)),
                ('quantity', models.CharField(default='', max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('no_of_remaining_items', models.CharField(default='', max_length=50)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.register')),
            ],
        ),
    ]
