# Generated by Django 4.2.2 on 2023-07-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_products',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
