# Generated by Django 4.2.2 on 2023-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0002_alter_shop_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_products',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
