# Generated by Django 4.2.2 on 2023-07-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management', '0003_alter_shop_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_products',
            name='product_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
