# Generated by Django 4.2.2 on 2023-07-03 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='date',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='document',
        ),
        migrations.CreateModel(
            name='Sub_scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_scheme', models.CharField(default='', max_length=50)),
                ('document', models.FileField(default='null', upload_to='')),
                ('date', models.DateField(default='null')),
                ('s_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officer_management.scheme')),
            ],
        ),
    ]
