# Generated by Django 4.2.2 on 2023-07-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0002_remove_scheme_date_remove_scheme_document_sub_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_scheme',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer_management.scheme'),
        ),
    ]
