# Generated by Django 4.2.2 on 2023-07-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_rename_user_farmer_register'),
        ('officer_management', '0004_alter_sub_scheme_s_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default='', max_length=50)),
                ('quantity', models.IntegerField(default='', max_length=50)),
                ('image', models.FileField(default='null', upload_to='')),
                ('product_type', models.CharField(default='', max_length=50)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.register')),
            ],
        ),
    ]
