# Generated by Django 4.2.2 on 2023-07-06 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_rename_user_farmer_register'),
        ('officer_management', '0005_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=50)),
                ('image', models.FileField(default='null', upload_to='')),
                ('date', models.DateField(default='null')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.register')),
            ],
        ),
    ]
