# Generated by Django 4.2.2 on 2023-07-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0006_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_scheme',
            name='date',
        ),
        migrations.AddField(
            model_name='sub_scheme',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sub_scheme',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sub_scheme',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
