# Generated by Django 4.2.2 on 2023-07-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0007_remove_sub_scheme_date_sub_scheme_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sub_scheme',
            name='sub_scheme',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
