# Generated by Django 4.2.2 on 2023-07-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0008_alter_products_quantity_alter_sub_scheme_sub_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
