# Generated by Django 4.2.2 on 2023-07-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0009_scheme_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='image',
        ),
    ]
