# Generated by Django 4.2.2 on 2023-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0011_products_no_of_remaining_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='no_of_remaining_items',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
