# Generated by Django 4.2.2 on 2023-07-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0012_alter_products_no_of_remaining_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
