# Generated by Django 4.2.2 on 2023-08-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0013_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(default='', max_length=150),
        ),
    ]
