# Generated by Django 4.2.2 on 2023-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0014_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('g', 'g'), ('ml', 'ml'), ('L', 'L')], default='Kg', max_length=250, verbose_name='Unit'),
        ),
    ]
