# Generated by Django 4.2.2 on 2023-08-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0015_products_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('g', 'g'), ('ml', 'ml'), ('L', 'L'), ('peice', 'peice')], default='peice', max_length=250, verbose_name='Unit'),
        ),
    ]
