# Generated by Django 4.2.2 on 2023-08-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0016_alter_products_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scheme',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
