# Generated by Django 4.2.2 on 2023-08-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0018_alter_scheme_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
    ]
