# Generated by Django 4.2.2 on 2023-07-14 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0006_register_aadhar_register_panchayath_register_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(default='', max_length=50)),
                ('street_name', models.CharField(default='', max_length=50)),
                ('place', models.CharField(default='', max_length=50)),
                ('pin_code', models.IntegerField(default='', max_length=50)),
                ('ration_card_no', models.IntegerField(default='', max_length=50)),
                ('total_land_owned', models.CharField(default='', max_length=50)),
                ('total_farming_land_owned', models.CharField(default='', max_length=50)),
                ('date_on_which_crop_failure_occured', models.CharField(default='', max_length=50)),
                ('reason_for_crop_failure', models.CharField(default='', max_length=50)),
                ('village', models.CharField(default='', max_length=50)),
                ('survey_no', models.IntegerField(default='', max_length=50)),
                ('sub_division_no', models.IntegerField(default='', max_length=50)),
                ('area_or_number_of_crops', models.CharField(default='', max_length=50)),
                ('damage_details', models.CharField(default='', max_length=50)),
                ('damaged_crop', models.CharField(default='', max_length=50)),
                ('phase_in_which_the_crops_damaged', models.CharField(default='', max_length=50)),
                ('farming_expenditure', models.CharField(default='', max_length=50)),
                ('expected_income_from_crops', models.CharField(default='', max_length=50)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.register')),
            ],
        ),
    ]
