# Generated by Django 4.2.2 on 2023-07-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_apply',
            name='date_on_which_crop_failure_occured',
            field=models.DateField(null=True),
        ),
    ]
