# Generated by Django 4.2.2 on 2023-07-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0003_rename_farmer_apply_apply_insurance_apply_fy_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='agro_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_rice_farming', models.CharField(default='', max_length=50)),
                ('no_of_coconut_trees', models.IntegerField(default=0, max_length=50)),
                ('no_of_pepper_plants', models.IntegerField(default=0, max_length=50)),
                ('area_of_vegetable_farming', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='land_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(default='', max_length=50)),
                ('survey_no', models.IntegerField(default=0, max_length=50)),
                ('area', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ration_card_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(default=0, max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=0, max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('education', models.CharField(default='', max_length=50)),
                ('job', models.CharField(default='', max_length=50)),
                ('marital_status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='age_of_the_house',
            field=models.CharField(choices=[('Less_Than_12_Years', 'Less_Than_12_Years'), ('More_Than_12_Years', 'More_Than_12_Years')], default='Less_than_12_years', max_length=250, verbose_name='AGE_OF_THE_HOUSE'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='annual_income',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='drinking_water',
            field=models.CharField(choices=[('Own_Well', 'Own_Well'), ('Public_Well', 'Public_Well'), ('Pond', 'Pond'), ('Public_tap', 'Public_tap')], default='Own_well', max_length=250, verbose_name='DRINKING_WATER'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='floor_area',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='floor_of_the_house',
            field=models.CharField(choices=[('Sand', 'Sand'), ('Cement', 'Cement'), ('Tiles', 'Tiles'), ('Mosaic', 'Mosaic'), ('Marble', 'Marble')], default='Tiles', max_length=250, verbose_name='FLOOR_OF_THE_HOUSE'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='hut',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='HUT'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='irrigation_facility',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='IRRIGATION_FACILITY'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='own_house',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='OWN_HOUSE'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='ownership_of_the_house',
            field=models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent'), ('Joint_Family', 'Joint_Family'), ('Relative_House', 'Relative_House'), ('Wasteland', 'Wasteland'), ('Others', 'Others')], default='Own', max_length=250, verbose_name='OWNERSHIP_OF_THE_HOUSE'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='permanent_resident',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='PERMANENT_RESIDENT'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='roof_of_the_house',
            field=models.CharField(choices=[('Terrace', 'Terrace'), ('Coconut_Leaf', 'Coconut_Leaf'), ('Grass', 'Grass'), ('Sun_Dried_tiles', 'Sun_Dried_tiles'), ('Concrete', 'Concrete')], default='Terrace', max_length=250, verbose_name='ROOF_OF_THE_HOUSE'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='toilet',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='TOILET'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='wall_of_the_house',
            field=models.CharField(choices=[('Bricks', 'Bricks'), ('Coconut Leaf', 'Coconut Leaf'), ('Mud', 'Mud'), ('Laterite_Stone', 'Laterite_Stone'), ('Holobricks', 'Holobricks')], default='Holobricks', max_length=250, verbose_name='WALL_OF_THE_HOUSE'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='wasteland',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='WASTELAND'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='age_of_the_applicant',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Minority', 'Minority'), ('Others', 'Others')], default='General', max_length=250, verbose_name='CATEGORY'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='house_no',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='ration_card_no',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='scheme_name',
            field=models.CharField(choices=[('Comprehensive Coconut Cultivation Development', 'Comprehensive Coconut Cultivation Development'), ('Modern vegetable cultivation', 'Modern vegetable cultivation'), ('Growing vegetables in pots', 'Growing vegetables in pots')], default='Comprehensive Coconut Cultivation Development', max_length=250, verbose_name='SCHEME_NAME'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='scheme_no',
            field=models.CharField(choices=[('115/23', '115/23'), ('113/23', '113/23'), ('117/23', '117/23')], default='115/23', max_length=250, verbose_name='SCHEME_NO'),
        ),
        migrations.AlterField(
            model_name='apply_insurance',
            name='pin_code',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='apply_insurance',
            name='ration_card_no',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='apply_insurance',
            name='sub_division_no',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='apply_insurance',
            name='survey_no',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='agro_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_management.agro_details'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='land_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_management.land_details'),
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='ration_card_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer_management.ration_card_details'),
        ),
    ]
