# Generated by Django 4.2.2 on 2023-07-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0004_agro_details_land_details_ration_card_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_fy_plan',
            name='scheme_no',
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='age_of_the_house',
            field=models.CharField(choices=[('Less_Than_12_Years', 'Less_Than_12_Years'), ('More_Than_12_Years', 'More_Than_12_Years')], default='Less_than_12_years', max_length=250, verbose_name='Age of the house'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Minority', 'Minority'), ('Others', 'Others')], default='General', max_length=250, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='drinking_water',
            field=models.CharField(choices=[('Own_Well', 'Own_Well'), ('Public_Well', 'Public_Well'), ('Pond', 'Pond'), ('Public_tap', 'Public_tap')], default='Own_well', max_length=250, verbose_name='Drinking water'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='floor_of_the_house',
            field=models.CharField(choices=[('Sand', 'Sand'), ('Cement', 'Cement'), ('Tiles', 'Tiles'), ('Mosaic', 'Mosaic'), ('Marble', 'Marble')], default='Tiles', max_length=250, verbose_name='Floor of the house'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='hut',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='Hut'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='irrigation_facility',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='Irrigation facility'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='own_house',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='Own house'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='ownership_of_the_house',
            field=models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent'), ('Joint_Family', 'Joint_Family'), ('Relative_House', 'Relative_House'), ('Wasteland', 'Wasteland'), ('Others', 'Others')], default='Own', max_length=250, verbose_name='Ownership of the house'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='permanent_resident',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='Permanent resident'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='roof_of_the_house',
            field=models.CharField(choices=[('Terrace', 'Terrace'), ('Coconut_Leaf', 'Coconut_Leaf'), ('Grass', 'Grass'), ('Sun_Dried_tiles', 'Sun_Dried_tiles'), ('Concrete', 'Concrete')], default='Terrace', max_length=250, verbose_name='Roof of the house'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='scheme_name',
            field=models.CharField(choices=[('Comprehensive Coconut Cultivation Development', 'Comprehensive Coconut Cultivation Development'), ('Modern vegetable cultivation', 'Modern vegetable cultivation'), ('Growing vegetables in pots', 'Growing vegetables in pots')], default='Comprehensive Coconut Cultivation Development', max_length=250, verbose_name='Scheme name'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='toilet',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='Toilet'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='wall_of_the_house',
            field=models.CharField(choices=[('Bricks', 'Bricks'), ('Coconut Leaf', 'Coconut Leaf'), ('Mud', 'Mud'), ('Laterite_Stone', 'Laterite_Stone'), ('Holobricks', 'Holobricks')], default='Holobricks', max_length=250, verbose_name='Wall of the house'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='wasteland',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=250, verbose_name='Wasteland'),
        ),
    ]
