# Generated by Django 4.2.2 on 2023-07-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_register_aadhar_register_panchayath_register_ward'),
        ('farmer_management', '0005_remove_apply_fy_plan_scheme_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_fy_plan',
            old_name='date',
            new_name='date_of_applying',
        ),
        migrations.AddField(
            model_name='apply_fy_plan',
            name='required_document_for_submission',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apply_insurance',
            name='date_of_applying',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='apply_insurance',
            name='required_document_for_submission',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Apply_Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(default='', max_length=50)),
                ('street_name', models.CharField(default='', max_length=50)),
                ('place', models.CharField(default='', max_length=50)),
                ('pin_code', models.IntegerField(default=0, max_length=50)),
                ('ration_card_no', models.IntegerField(default=0, max_length=50)),
                ('annual_income', models.CharField(default='', max_length=50)),
                ('total_land_owned', models.CharField(default='', max_length=50)),
                ('total_farming_land_owned', models.CharField(default='', max_length=50)),
                ('village', models.CharField(default='', max_length=50)),
                ('survey_no', models.IntegerField(default=0, max_length=50)),
                ('sub_division_no', models.IntegerField(default=0, max_length=50)),
                ('crop_type', models.CharField(default='', max_length=50)),
                ('irrigation_method', models.CharField(default='', max_length=50)),
                ('water_source', models.CharField(default='', max_length=50)),
                ('amount_of_water_required', models.CharField(default='', max_length=50)),
                ('water_schedule', models.CharField(default='', max_length=50)),
                ('reasons_for_applying', models.CharField(default='', max_length=150)),
                ('required_document_for_submission', models.FileField(null=True, upload_to='')),
                ('date_of_applying', models.CharField(default='', max_length=150)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.register')),
            ],
        ),
    ]
