# Generated by Django 4.2.2 on 2023-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0006_rename_date_apply_fy_plan_date_of_applying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='age_of_the_house',
            field=models.CharField(choices=[('Less_Than_12_Years', 'Less_Than_12_Years'), ('More_Than_12_Years', 'More_Than_12_Years')], default='Less than 12_years', max_length=250, verbose_name='Age of the house'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='drinking_water',
            field=models.CharField(choices=[('Own_Well', 'Own_Well'), ('Public_Well', 'Public_Well'), ('Pond', 'Pond'), ('Public_tap', 'Public_tap')], default='Own well', max_length=250, verbose_name='Drinking water'),
        ),
    ]
