# Generated by Django 4.2.2 on 2023-07-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0007_alter_apply_fy_plan_age_of_the_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='age_of_the_house',
            field=models.CharField(choices=[('Less Than 12 Years', 'Less Than 12 Years'), ('More Than 12 Years', 'More Than 12 Years')], default='Less than 12 years', max_length=250, verbose_name='Age of the house'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='drinking_water',
            field=models.CharField(choices=[('Own Well', 'Own Well'), ('Public Well', 'Public Well'), ('Pond', 'Pond'), ('Public tap', 'Public tap')], default='Own well', max_length=250, verbose_name='Drinking water'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='hut',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=250, verbose_name='Hut'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='ownership_of_the_house',
            field=models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent'), ('Joint Family', 'Joint Family'), ('Relative House', 'Relative House'), ('Wasteland', 'Wasteland'), ('Others', 'Others')], default='Own', max_length=250, verbose_name='Ownership of the house'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='roof_of_the_house',
            field=models.CharField(choices=[('Terrace', 'Terrace'), ('Coconut_Leaf', 'Coconut_Leaf'), ('Grass', 'Grass'), ('Sun Dried tiles', 'Sun Dried tiles'), ('Concrete', 'Concrete')], default='Terrace', max_length=250, verbose_name='Roof of the house'),
        ),
        migrations.AlterField(
            model_name='apply_fy_plan',
            name='wall_of_the_house',
            field=models.CharField(choices=[('Bricks', 'Bricks'), ('Coconut Leaf', 'Coconut Leaf'), ('Mud', 'Mud'), ('Laterite Stone', 'Laterite Stone'), ('Holobricks', 'Holobricks')], default='Holobricks', max_length=250, verbose_name='Wall of the house'),
        ),
    ]
