# Generated by Django 4.2.2 on 2023-07-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_register_aadhar_register_panchayath_register_ward'),
        ('farmer_management', '0009_alter_apply_fy_plan_age_of_the_applicant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=50)),
                ('image_or_video', models.FileField(upload_to='')),
                ('date_and_time', models.DateField(null=True)),
                ('status', models.CharField(default='', max_length=50)),
                ('oid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farmer.register')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farmer.register')),
            ],
        ),
    ]
