# Generated by Django 4.2.2 on 2023-07-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0010_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
