# Generated by Django 4.2.2 on 2023-07-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0012_alter_query_image_or_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='image_or_video',
            new_name='image',
        ),
    ]
