# Generated by Django 4.2.2 on 2023-07-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0013_rename_image_or_video_query_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='query',
            name='status',
        ),
    ]
