# Generated by Django 4.2.2 on 2023-07-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer_management', '0013_alter_products_price'),
        ('farmer', '0006_register_aadhar_register_panchayath_register_ward'),
        ('farmer_management', '0014_remove_query_date_and_time_remove_query_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='', max_length=150)),
                ('quantity', models.CharField(default='', max_length=150)),
                ('time', models.DateField(default='', max_length=150)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officer_management.products')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.register')),
            ],
        ),
    ]
