# Generated by Django 4.2.2 on 2023-07-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0015_product_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_booking',
            name='time',
            field=models.CharField(default='', max_length=150),
        ),
    ]
