# Generated by Django 4.2.2 on 2023-07-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0016_alter_product_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_booking',
            name='time',
        ),
    ]
