# Generated by Django 4.2.2 on 2023-07-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0017_remove_product_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='response',
            field=models.CharField(default='', max_length=200),
        ),
    ]
