# Generated by Django 4.2.2 on 2023-08-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_rename_aadhar_register_aadhar_number_and_more'),
        ('farmer_management', '0018_query_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_krishibhavan', models.CharField(default='', max_length=50)),
                ('place', models.CharField(default='', max_length=50)),
                ('house_number', models.IntegerField(default=0, max_length=50)),
                ('village', models.CharField(default='', max_length=50)),
                ('survey_number', models.IntegerField(default=0, max_length=50)),
                ('land_area', models.CharField(default='', max_length=50)),
                ('farm_area', models.CharField(default='', max_length=50)),
                ('name_of_the_crops', models.CharField(default='', max_length=50)),
                ('number_or_area_of_the_crops', models.CharField(default='', max_length=50)),
                ('horse_power', models.CharField(default='', max_length=50)),
                ('KSEB_consumer_number', models.IntegerField(default=0, max_length=50)),
                ('monthly_amount', models.CharField(default='', max_length=50)),
                ('required_document_for_submission', models.FileField(null=True, upload_to='')),
                ('date_of_applying', models.CharField(default='', max_length=150)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.register')),
            ],
        ),
        migrations.RemoveField(
            model_name='apply_irrigation',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='apply_fy_plan',
            name='agro_id',
        ),
        migrations.RemoveField(
            model_name='apply_fy_plan',
            name='land_id',
        ),
        migrations.RemoveField(
            model_name='apply_fy_plan',
            name='ration_card_id',
        ),
        migrations.DeleteModel(
            name='agro_details',
        ),
        migrations.DeleteModel(
            name='Apply_Irrigation',
        ),
        migrations.DeleteModel(
            name='land_details',
        ),
        migrations.DeleteModel(
            name='Ration_card_details',
        ),
    ]
