# Generated by Django 4.2.2 on 2023-08-08 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_rename_aadhar_register_aadhar_number_and_more'),
        ('farmer_management', '0019_apply_electricity_remove_apply_irrigation_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_State_Horticulture_Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_krishibhavan', models.CharField(default='', max_length=50)),
                ('scheme_name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('local_body', models.CharField(default='', max_length=50)),
                ('ward_name', models.CharField(default='', max_length=50)),
                ('block', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
                ('village', models.CharField(default='', max_length=50)),
                ('survey_number', models.IntegerField(default=0, max_length=50)),
                ('total_land', models.CharField(default='', max_length=50)),
                ('bank_loan', models.CharField(default='', max_length=50)),
                ('bank_name', models.CharField(default='', max_length=50)),
                ('account_number', models.IntegerField(default='', max_length=50)),
                ('required_document_for_submission', models.FileField(null=True, upload_to='')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.register')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_Pradhan_Manthri_Kisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_krishibhavan', models.CharField(default='', max_length=50)),
                ('block', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
                ('village', models.CharField(default='', max_length=50)),
                ('fathers_name', models.CharField(default='', max_length=50)),
                ('post_office', models.CharField(default='', max_length=50)),
                ('pin_code', models.IntegerField(default=0, max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('date_of_birth', models.DateField(default='', max_length=150)),
                ('ration_card_number', models.IntegerField(default=0, max_length=50)),
                ('bank_account_number', models.IntegerField(default=0, max_length=50)),
                ('bank_name', models.CharField(default='', max_length=50)),
                ('branch_name', models.CharField(default='', max_length=50)),
                ('IFSC_code', models.CharField(default='', max_length=50)),
                ('survey_number', models.IntegerField(default=0, max_length=50)),
                ('land_area', models.CharField(default='', max_length=50)),
                ('ward_name', models.CharField(default='', max_length=50)),
                ('thaluk', models.CharField(default='', max_length=50)),
                ('required_document_for_submission', models.FileField(null=True, upload_to='')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.register')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='', max_length=50)),
                ('block', models.CharField(default='', max_length=50)),
                ('name_of_krishibhavan', models.CharField(default='', max_length=50)),
                ('pincode', models.IntegerField(default=0, max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('village', models.CharField(default='', max_length=50)),
                ('survey_number', models.IntegerField(default=0, max_length=50)),
                ('land_area', models.CharField(default='', max_length=50)),
                ('farming_details', models.CharField(default='', max_length=50)),
                ('years_of_experience', models.CharField(default='', max_length=50)),
                ('account_number', models.IntegerField(default='', max_length=50)),
                ('bank_name', models.CharField(default='', max_length=50)),
                ('branch_name', models.CharField(default='', max_length=50)),
                ('required_document_for_submission', models.FileField(null=True, upload_to='')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.register')),
            ],
        ),
    ]
