# Generated by Django 4.2.2 on 2023-08-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_management', '0021_apply_insurance_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_booking',
            name='amount',
            field=models.CharField(default='', max_length=150),
        ),
    ]
